### ISSUE TITLE
Moving 5th workshop entries to _events_past leads to error

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/parallel-in-time.github.io#124]
If the entries for the 5th workshop are moved from _events_upcoming to _events_past leads to error

  Liquid Exception: comparison of NilClass with String failed in _includes/asides/event_subnav.html, included in _layouts/page_event.html
jekyll 3.1.1 | Error:  comparison of NilClass with String failed

when running `jekyll build`.

The corresponding forked branch can be found here: https://github.com/danielru/parallel-in-time.github.io/tree/add/post_workshop_news

**Comment by pancetta** [comment]
This disappears if you remove the `subtitle` keyword from the files. Yet, then the subpages disappear, too.

@torbjoernk Any idea how to fix this? It seems that `_includes/asides/event_subnav.html` does not work for past events (for whatever reason).

**Comment by pancetta** [comment]
This also goes away if all past events get the `subtitle` keyword, but it cannot be empty.

**Comment by danielru** [comment]
Guess that makes sense -- the NilClass probably comes from an event not having the entry. Is there any disadvantage to adding a subtitle to all past events?

**Comment by pancetta** [comment]
Yeah, we could do that. But the title cannot be empty...

**Comment by danielru** [comment]
Okay, will take a look at that later.

**Comment by danielru** [comment]
Fixed by #126
