### ISSUE TITLE
Overflow of links at project sites

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/parallel-in-time.github.io#158]
This does not look nice, see e.g. [here](http://www.parallelintime.org/projects/borissdc.html). We could think about having something like [this](https://jlesc.github.io/events/7th-jlesc-workshop/).

**Comment by pancetta** [comment]
Check this out: https://github.com/JLESC/jlesc.github.io/blob/source/_includes/asides/event_meta.html#L17

**Comment by danielru** [comment]
Related to issue #61 - I like the solution you showed that just displays a symbol. Would you know how to implement this?

**Comment by pancetta** [comment]
Fixed by efec22e.
