### ISSUE TITLE
Open positions

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/parallel-in-time.github.io#172]
Should/can we advertise open positions on this website? If yes, where? As a simple news item (easy and accessible) or in a separate category like "career" (will have to include that) or so?

**Comment by danielru** [comment]
I'd say putting them as news items should be fine? Unless we have a relatively large number of positions, I don't think a new category is really warranted.

**Comment by pancetta** [comment]
Yeah, I think so, too.

**Comment by pancetta** [comment]
Closed via #173
