### ISSUE TITLE
Updated references now showing on website

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/parallel-in-time.github.io#25]
For some reason, the updates from the last PR are not visible on the website although the files in the source branch have changed:

E.g. in the [MLSDC](https://github.com/Parallel-in-Time/parallel-in-time.github.io/blob/source/_includes/references/speck2013_mlsdc.html) paper, the source file correctly shows BIT Numerical Mathematics as journal while the [website](http://parallel-in-time.github.io/codes/pypint.html) still shows arxiv.

This is not merely a caching issue, I tried it from different computers with different browsers.

**Comment by torbjoernk** [comment]
Redeploying the site fixed this. Something went wrong without warnings/errors while deploying.
