### ISSUE TITLE
add instructions in wiki for fetching/merging upstream information

### ISSUE THREAD

**Issue by ongbw** [Parallel-in-Time/parallel-in-time.github.io#41]
instructions in wiki are reasonable for new users to fork and add new information.  However, lacking instructions on how they can come back and make edits in the future.  Maybe the correct process  is to restart the entire procedure (create new fork, clone, etc).  My preferred workflow is to merge from upstream.  Is it worth having documentation on that?

**Comment by danielru** [comment]
Hm, do you have a nice tutorial for this we can link to? You are right, typically one would not want to fork again every time...

**Comment by ongbw** [comment]
most tutorials for merging from upstream will only work with the "master branch", additional notes will be needed for the "source branch" if the user is not git savvy.  This tutorial is probably a good start:
https://help.github.com/articles/syncing-a-fork/

**Comment by danielru** [comment]
Thanks! I modified the first bullet point in the wiki a bit. Also nice to see that RIDC is now also on our website :+1:
