### ISSUE TITLE
Links in references not parsed

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/parallel-in-time.github.io#44]
In the current version, the links under references appear in markdown syntax and are not parsed into links: For example, the link in the first entry is

`[http://arxiv.org/abs/1503.02094v1](http://arxiv.org/abs/1503.02094v1)`

instead of

[http://arxiv.org/abs/1503.02094v1](http://arxiv.org/abs/1503.02094v1)

**Comment by danielru** [comment]
Note: When delivering the site locally with jekyll, the URLs are correctly generated - the problem is only at the version delivered at parallelintime.org

**Comment by torbjoernk** [comment]
Finally, I had another look into that issue. And can reproduce the same error locally. @danielru what setup do you have locally? What Ruby version are you using and when the specific gemset activated for local testing, what does `gem list` tell you?

The site is generated with Ruby 2.1.5 and the following gems:
```
bibtex-ruby (4.0.14)
bigdecimal (1.2.4)
blankslate (2.1.2.4)
bundler (1.7.6)
bundler-unload (1.0.2)
celluloid (0.16.0)
citeproc (1.0.2)
citeproc-ruby (1.1.0)
classifier-reborn (2.0.3)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
colorator (0.1)
csl (1.4.3)
csl-styles (1.0.1.6)
execjs (2.6.0)
executable-hooks (1.3.2)
fast-stemmer (1.0.2)
ffi (1.9.10)
gem-wrappers (1.2.7)
hitimes (1.2.3, 1.2.2)
io-console (0.4.2)
jekyll (2.5.3)
jekyll-coffeescript (1.0.1)
jekyll-gist (1.3.4, 1.3.3)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.3.0)
jekyll-scholar (4.5.0)
jekyll-watch (1.3.0, 1.2.1)
json (1.8.1)
kramdown (1.8.0)
latex-decode (0.2.2)
liquid (2.6.3)
listen (3.0.3, 2.10.1)
mercenary (0.3.5)
minitest (4.7.5)
namae (0.10.1)
octopress (3.0.11)
octopress-deploy (1.3.0)
octopress-escape-code (2.0.6)
octopress-hooks (2.6.1)
parslet (1.5.0)
posix-spawn (0.3.11)
psych (2.0.5)
pygments.rb (0.6.3)
rake (10.1.0)
rb-fsevent (0.9.6, 0.9.5)
rb-inotify (0.9.5)
rdoc (4.1.0)
redcarpet (3.3.2)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
safe_yaml (1.0.4)
sass (3.4.18, 3.4.17)
stringex (2.5.2)
test-unit (2.1.5.0)
timers (4.0.4, 4.0.1)
titlecase (0.1.1)
toml (0.1.2)
unicode (0.4.4.2)
yajl-ruby (1.2.1)
```

**Comment by danielru** [comment]
I am using `ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]`.

The output of `gem list` is

`
- bibtex-ruby (4.0.13)
- bigdecimal (1.2.4)
- blankslate (2.1.2.4)
- bundler (1.10.5, 1.7.6)
- bundler-unload (1.0.2)
- celluloid (0.15.2)
- citeproc (1.0.2)
- citeproc-ruby (1.1.0)
- classifier (1.3.4)
- coffee-script (2.3.0)
- coffee-script-source (1.7.1)
- colorator (0.1)
- csl (1.4.2)
- csl-styles (1.0.1.6)
- execjs (2.2.1)
- executable-hooks (1.3.2)
- fast-stemmer (1.0.2)
- ffi (1.9.3)
- gem-wrappers (1.2.7)
- io-console (0.4.2)
- jekyll (2.1.1)
- jekyll-coffeescript (1.0.0)
- jekyll-gist (1.1.0)
- jekyll-paginate (1.0.0)
- jekyll-sass-converter (1.0.0)
- jekyll-scholar (4.3.5)
- jekyll-watch (1.0.0)
- json (1.8.1)
- kramdown (1.4.0)
- latex-decode (0.2.2)
- liquid (2.6.1)
- listen (2.7.9)
- mercenary (0.3.4)
- minitest (4.7.5)
- namae (0.10.1)
- octopress (3.0.0.rc.13)
- octopress-deploy (1.0.0.rc.10)
- octopress-filters (1.1.1)
- octopress-hooks (2.0.0)
- parslet (1.5.0)
- posix-spawn (0.3.8)
- psych (2.0.5)
- pygments.rb (0.6.0)
- rake (10.1.0)
- rb-fsevent (0.9.4)
- rb-inotify (0.9.5)
- rdoc (4.1.0)
- redcarpet (3.1.2)
- rubygems-bundler (1.4.4)
- rubypants-unicode (0.2.3)
- rvm (1.11.3.9)
- safe_yaml (1.0.3)
- sass (3.3.10)
- stringex (2.5.2)
- test-unit (2.1.5.0)
- timers (1.1.0)
- titlecase (0.1.1)
- toml (0.1.1)
- unicode (0.4.4.2)
- yajl-ruby (1.1.0)
`

**Comment by torbjoernk** [comment]
*yeah* finally ...

**Comment by danielru** [comment]
For some strange reason, the issue resurfaced. On the website, the links are again not correctly parsed :(

**Comment by torbjoernk** [comment]
Not so strage reason: the Jekyll/scholar plugin has changed its internals after some version upgrades, thus the previous monkey-patch didn't work any more.
