### ISSUE TITLE
Would you please delete the "\"s in the downloaded bib file?

### ISSUE THREAD

**Issue by eccstartup** [Parallel-in-Time/parallel-in-time.github.io#62]
Jabref won't open the right link if there is `\_` rather than `_` in `url` field.

**Comment by eccstartup** [comment]
Thanks. :+1:

**Comment by memmett** [comment]
@eccstartup Next time a patch fixing the issue would be greatly appreciated (and even faster than @danielru)!

**Comment by eccstartup** [comment]
I didn't, because I did not find the bib file in this repo.

**Comment by torbjoernk** [comment]
[It's described in the wiki](https://github.com/Parallel-in-Time/parallel-in-time.github.io/wiki/Adding-Publications).

**Comment by memmett** [comment]
Let's change the default checkout branch... this has happened a couple
times :)

**Comment by torbjoernk** [comment]
That would break GitHub Pages, which is used to serve the page.

**Comment by memmett** [comment]
There must be a cleaner way of doing this.  Can we have two repos?

**Comment by torbjoernk** [comment]
Having the `master` branch with the generated page and `source` being the _source_ branch is the default and suggested way of maintaining and deploying static pages via Jekyll and GitHub pages.
