### ISSUE TITLE
New Papers for bibbot!

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/parallel-in-time.github.io#621]
https://doi.org/10.1002/qj.3302

**Comment by tlunet** [comment]
@pancetta I cannot label this as `food-for-bibot` :sweat_smile:

**Comment by pancetta** [comment]
Huh? You cannot select this label?

**Comment by tlunet** [comment]
Nope. I believe one can set a label only with some specific rights

**Comment by tlunet** [comment]
I can change the label now, thanks @pancetta !
